spring:

  #DATASOURCE CONFIGURATION
  application:
    name: movie-ticket-booking-system-api
  datasource:
    url: jdbc:mysql://localhost:3306/movie-ticket-booking-db
    username: root
    password: Krish8819
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
